name: "Checkov GitHub Action"
on:
  pull_request:
    branches: [test, dev, qa, prod, main]

jobs:
  checkov:
    name: checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          token: ${{ secrets.ENGINEERING_GITHUB_PERSONAL_ACCESS_TOKEN }}
      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
          quiet: true # optional: display only failed checks
