# This GitHub Action should be located at https://github.com/honestbank/gitops-library/blob/main/github/actions/terratest.yml
# When making any changes, please submit a PR to the file/repo above as well.

name: terratest

on:
  pull_request

jobs:
  terratest:
    name: terratest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0 # See https://github.com/hashicorp/terraform/issues/28524
          terraform_wrapper: false
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          cd test
          go test -v -timeout 30m
