name: terratest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terratest:
    name: terratest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0
          terraform_wrapper: false
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          cd test
          go test -v -timeout 30m
