# This GitHub Action should be located at https://github.com/honestbank/gitops-library/blob/main/github/actions/terraform.yml
# When making any changes, please submit a PR to the file/repo above as well.
#
# Required variables/secrets:
# TF_WORKSPACE: The Terraform Cloud workspace suffix (usually the stage/environment)
# TF_API_TOKEN: Terraform Cloud API token

name: Terraform GitHub Actions

on:
  pull_request

env:
  tf_version: "0.15.0" # See https://github.com/hashicorp/terraform/issues/28524
  tf_working_dir: "."
  TF_WORKSPACE: ${{ github.base_ref }}
jobs:
  terraform:
    name: "Terraform - Format, Init, Validate, Plan, Fail on Change"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true
      - uses: actions/github-script@v4
        continue-on-error: true
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`${process.env.PLAN}\`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
